title: <p align="center"> Sai Yaswanth S </p>
logo: /assets/img/logo.png

description:
  <p align="center"> |
  <a href="https://www.linkedin.com/in/sai-yaswanth-sigirala-14974317a/">LinkedIn</a> |
  <a href="https://github.com/yeswanth1098">GitHub</a>
  
  <br>   
  I'm learning Data Science in Upgrad.
  <br>
  </p>



theme: jekyll-theme-minimal
